// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// getIndexFromCoords
String getIndexFromCoords(double lat, double lon, int resolution);
RcppExport SEXP _h3r_getIndexFromCoords(SEXP latSEXP, SEXP lonSEXP, SEXP resolutionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type lat(latSEXP);
    Rcpp::traits::input_parameter< double >::type lon(lonSEXP);
    Rcpp::traits::input_parameter< int >::type resolution(resolutionSEXP);
    rcpp_result_gen = Rcpp::wrap(getIndexFromCoords(lat, lon, resolution));
    return rcpp_result_gen;
END_RCPP
}
// getBoundingHexFromCoords
List getBoundingHexFromCoords(double lat, double lon, int resolution);
RcppExport SEXP _h3r_getBoundingHexFromCoords(SEXP latSEXP, SEXP lonSEXP, SEXP resolutionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type lat(latSEXP);
    Rcpp::traits::input_parameter< double >::type lon(lonSEXP);
    Rcpp::traits::input_parameter< int >::type resolution(resolutionSEXP);
    rcpp_result_gen = Rcpp::wrap(getBoundingHexFromCoords(lat, lon, resolution));
    return rcpp_result_gen;
END_RCPP
}
// getBoundingHexFromIndex
List getBoundingHexFromIndex(String index);
RcppExport SEXP _h3r_getBoundingHexFromIndex(SEXP indexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< String >::type index(indexSEXP);
    rcpp_result_gen = Rcpp::wrap(getBoundingHexFromIndex(index));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_h3r_getIndexFromCoords", (DL_FUNC) &_h3r_getIndexFromCoords, 3},
    {"_h3r_getBoundingHexFromCoords", (DL_FUNC) &_h3r_getBoundingHexFromCoords, 3},
    {"_h3r_getBoundingHexFromIndex", (DL_FUNC) &_h3r_getBoundingHexFromIndex, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_h3r(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
