# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' getIndexFromCoords returns the h3 index from a lat, lon, and resolution
#' @param lat latitude in degrees
#' @param lon longitude in degrees
#' @param resolution resolution, higher is more granular
getIndexFromCoords <- function(lat, lon, resolution) {
    .Call(`_h3r_getIndexFromCoords`, lat, lon, resolution)
}

#' getBoundingHexFromCoords returns the h3 bounding hex from a lat, lon and resolution
#' @param lat latitude in degrees
#' @param lon longitude in degrees
#' @param resolution resolution, higher is more granular
getBoundingHexFromCoords <- function(lat, lon, resolution) {
    .Call(`_h3r_getBoundingHexFromCoords`, lat, lon, resolution)
}

#' getBoundingHexFromIndex takes an h3 index and returns the corresponding bounding hex
#' @param index h3 index as a hex representation character vector. See \code{\link{getIndexFromCoords}}
getBoundingHexFromIndex <- function(index) {
    .Call(`_h3r_getBoundingHexFromIndex`, index)
}

